stages:
  - build
  - deploy


image: docker.arvancloud.ir/docker:latest

services:
  - docker:dind

variables:
  REPO: 127.0.0.1:8082/docker
  PROJECT_NAME: onlinestore_core # Change this to your app name
  NAMESPACE: backend
  VER: $REPO/$NAMESPACE/$PROJECT_NAME:$CI_COMMIT_TAG

stages:
  - build_docker_image  
  - deploy_docker_image  

docker_build:
  stage: build_docker_image
  script:
    - echo "docker build stage ..."
    - if [[ $(expr match $CI_COMMIT_TAG '\([0-9]\{1,2\}\)\.\([0-9]\{1,2\}\)\.\([0-9]\{1,2\}\)') != 0 ]]; then echo "tag is ok!"; else echo "tag is invalid..." && exit 1; fi
    - echo "test" | docker login http://127.0.0.1:8082 -u "dev" --password-stdin
    - echo $VER
    - docker build -t $VER -f Dockerfile .
    - docker push $VER
  only:
    - tags

docker_deploy:
  stage: deploy_docker_image
  image: docker.arvancloud.ir/docker:26.1.2-alpine3.19
  services:
    - docker:dind
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
    - echo "$SSH_PRIVATE_KEY"
    - echo "$SSH_PRIVATE_KEY" | base64 -d 
    - mkdir -p ~/.ssh
    - echo $SWARM_MANAGER_IP
    - ssh-keyscan -p 2345 -H $SWARM_MANAGER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
  script:
    - export VER=$VER
    - docker stack deploy -c docker-compose.yml onlineStoreCore --with-registry-auth --prune
  only:
    - tags
