version: "3.9"

x-deploy: &deploy-section
  mode: replicated
  replicas: 1
  restart_policy:
    condition: any
    max_attempts: 3
    delay: 5s
    window: 30s
  update_config:
    parallelism: 2
    delay: 5s
    failure_action: rollback
    order: stop-first
  rollback_config:
    parallelism: 2
    delay: 5s
    failure_action: pause
    order: stop-first

x-logging: &logging-section
  driver: "json-file"
  options:
    max-size: 10m
    max-file: "3"
    tag: backend_onlinestore

services:
  onlinestore-core:
    image: ${VER}
    ports:
      - "2367:7000"
    deploy:
      <<: *deploy-section
    networks:
      - Production_Database_Network
    logging:
      <<: *logging-section

networks:
  Production_Database_Network:
    external: true # Mark the network as external since it already exists
